Multi distro travis
ipa320/cob_navigation pull request #83
Opened 2017-03-05 13:36 UTC by ipa-fxm

includes #79 

no kinetic_dev needed

2017-03-15 08:28 UTC, ipa-fxm commented
remove cob4-10 after https://github.com/ipa320/cob_robots/pull/634

2017-03-20 07:49 UTC, mgruhler requested changes

2017-03-20 07:49 UTC, ipa-mig commented on cob_navigation_global/CMakeLists.txt
> +  find_package(roslaunch REQUIRED)
why do you `find_package` all those packages directly and not via catkin?

2017-03-20 07:49 UTC, ipa-mig commented on cob_navigation_global/CMakeLists.txt
> +    foreach(env ${cob_default_env_config_ENVLIST})
hmm, probably because of those lists? Can't you access them this way if you find them via catkin? But then, what about `roslaunch`?

2017-03-20 07:52 UTC, ipa-fxm commented on cob_navigation_global/CMakeLists.txt
> +  find_package(roslaunch REQUIRED)
because they are `test_depends`

2017-03-20 08:01 UTC, ipa-mig commented on cob_navigation_global/CMakeLists.txt
> +  find_package(roslaunch REQUIRED)
ah, right :-) missed that.

2017-03-20 08:01 UTC, mgruhler approved these changes

2017-03-20 10:20 UTC, NadiaHG approved these changes

2017-03-20 11:43 UTC, merged