restructure nav config
ipa320/cob_navigation pull request #85
Opened 2017-04-06 08:55 UTC by ipa-fxm

related to https://github.com/ipa320/cob_robots/pull/652

2017-04-06 11:47 UTC, ipa-fxm commented
I consider this done so far....
In https://github.com/ipa320/msh/pull/684, I am testing against all related feature branches...

@ipa-mig @ipa-jba @ipa-fmw 
please review

2017-04-07 06:33 UTC, mgruhler requested changes
@ipa-fxm what is your opinion?

2017-04-07 06:33 UTC, ipa-mig commented on cob_navigation_global/launch/2dnav_linear.launch
> +  <arg name="map" default="$(find cob_default_env_config)/envs/$(arg robot_env)/map.yaml" />
In order to make those launch files more easily usable in the new structure, should we add a launch arg for the env package as well?

2017-04-07 06:33 UTC, ipa-mig commented on cob_navigation_global/launch/2dnav_linear.xml
> +    <rosparam file="$(find cob_navigation_config)/robots/$(arg robot)/nav/linear_ctrl_params.yaml" command="load" />
In order to make those launch files more easily usable in the new structure, should we add a launch arg for the config package as well?

(holds for the other launch files as well, I'm not commenting every occurance now...)

2017-04-07 08:35 UTC, ipa-fmw commented on cob_navigation_global/launch/2dnav_linear.launch
> +  <arg name="map" default="$(find cob_default_env_config)/envs/$(arg robot_env)/map.yaml" />
yes, please use same args as for ipa_navigation

2017-04-07 12:44 UTC, ipa-fxm commented on cob_navigation_global/launch/2dnav_linear.launch
> +  <arg name="map" default="$(find cob_default_env_config)/envs/$(arg robot_env)/map.yaml" />
done

2017-04-10 06:35 UTC, mgruhler approved these changes
merge together with ipa320/cob_environments#120

2017-04-10 16:08 UTC, merged