Code restructuring to provide map accessibility check as ROS service and C++ library
ipa320/cob_navigation pull request #87
Opened 2017-06-22 06:23 UTC by ipa-rmb

Just a separation of the core functionality from the ROS service message interface. Map accessibility can now be checked for a set of points or a circle by including a C++ library (new) or by calling the ROS service (the old way).

Function and interface should still be 100% the same, just that the functions are moved to a separate file and can be used as lib as well.

Can someone ( @ipa-bnm , @ipa-fmw, @ipa-fxm ) please confirm that the software is still doing its job if it is used for MSH?

2017-06-22 10:47 UTC, ipa-fmw commented
@fmw-hb will test for MSH. Please wait for test result before merging

2017-06-23 07:45 UTC, HannesBachter requested changes
otherwise works as expected

2017-06-23 07:45 UTC, fmw-hb commented on cob_map_accessibility_analysis/ros/src/map_accessibility_analysis.cpp
> +#define __DEBUG_DISPLAYS__
please comment that out

2017-06-23 08:06 UTC, ipa-rmb commented on cob_map_accessibility_analysis/ros/src/map_accessibility_analysis.cpp
> +#define __DEBUG_DISPLAYS__
Sorry, I forgot to remove the output...

2017-06-23 08:57 UTC, HannesBachter approved these changes
:+1:

2017-06-23 12:05 UTC, floweisshardt approved these changes
approved by @fmw-hb

2017-06-26 08:51 UTC, ipa-rmb commented
I have no permissions to merge. Can you do it please?

2017-07-03 14:37 UTC, ipa-fxm commented
Travis is happy now...merging

2017-07-03 14:37 UTC, merged